### ISSUE TITLE
Album artwork sizes.

### ISSUE THREAD

**Issue by ThePlayingGoblin** [TripleFrequency/AthamePlugin.Deezer#1]
Very minor and not very important. The option to pick our own artwork size (500x500, 800x800, 1000x1000, and 1200x1200), something deezloader had.

**Comment by TripleFrequency** [comment]
I just added support for this in the new release. There is now a drop-down in your settings to select 56x56, 250x250, 500x500, and 1000x1000 for the large version of images. The default is 1000x1000.

There is also a (hidden) option for thumbnail sizes. I didn't add it into the GUI because it could get confusing, and the thumbnails aren't really used. It is stored in the config, but not used currently.

**Comment by TripleFrequency** [comment]
This has been improved lots in Version 1.3-RC1. You can how directly modify the size to whatever you want directly in the config, but in the application you can now choose 50x50, 125x125, 250x250, 500x500, 1000x1000, and 1200x1200.
