### ISSUE TITLE
New stuff can't be added.

### ISSUE THREAD

**Issue by Refelinux** [TripleFrequency/AthamePlugin.Deezer#24]
After version of plugin 1.3.0 i can't added all new stuff when albums arrived to my country. For example this - http://www.deezer.com/album/52753402 (Maybe you can already add it, i do not know.)
There was no such problem before, but the albums were without a cover, but now I absolutely can not add them in athame. Most likely I can add them when they come out in all countries.

To check, you can see here the coming releases. When you have 00:00 on the clock, you will see new albums in your account, but you will not be able to add them to athame.
I hope you can fix it...
http://www.djtunes.com/music/home?view=releases&status=upcoming&page=5&sort=release_date

i don't know how can i copy this text, but i pin the screen of error. https://imgur.com/ubDvWoq

**Comment by TripleFrequency** [comment]
I don't quite follow the issue here. While I could possibly refine it so that you don't see an error like that, it makes sense. The tracks aren't released yet, so you shouldn't see them. I think all the times are EST, so it may be the 4th where you live, but not where the release is happening.

**Comment by Refelinux** [comment]
The tracks aren't released yet? No, of course them released ! That's why i wrote to you... I try download new releases that was released for my country, but i can't ! You are really can't help?

**Comment by jonaaa20** [comment]
So, @TripleFrequency, the plugin can't download songs that aren't available on my country?

**Comment by TripleFrequency** [comment]
@Refelinux I am saying for the album in particular you linked, and same for the djtunes. I am talking about the timezones of those releases not being accurate. When I go to the album you linked, I see this:
![image](https://user-images.githubusercontent.com/6166013/33532850-32887584-d86b-11e7-9c9b-6c12eed8a786.png)
Which clearly shows the songs are not released yet. I am suggesting that Deezer doesn't convert the timezones properly, so it displays for you that it is released, when it isn't.

When it is actually released, there should be no problem.

Also, @jonaaa20, from my testing after my recent fix for songs that wouldn't download, I have found that it *will* download songs not normally available in your country.

**Comment by Refelinux** [comment]
What are you talking about? I repeat! Your version of the plugin 1.2.7 does not have this problem, but 1.3 has this problem! Now it is clear? If you didn't get the album out in your country, it does not mean that it did not released... I say AGAIN. Take this album NOW - add it to version 1.2.7 and add to 1.3 and just CHECK - https://www.deezer.com/ru/album/52757852

**Comment by jonaaa20** [comment]
No need to be rude bro.

**Comment by Refelinux** [comment]
Sorry, I really didn't mean to!

**Comment by TripleFrequency** [comment]
Are you able to play the songs *on* Deezer? (before downloading)

**Comment by Refelinux** [comment]
Yes, of course ! As i said i even can download it, but with 1.2.7 version

**Comment by Refelinux** [comment]
So, will you do anything with this?

**Comment by TripleFrequency** [comment]
I can't flip a switch and fix this, and I don't fully grasp the issue at hand. I'll keep this in mind, but ultimately, without more meaningful data, I can't diagnose the issue. Do you have more examples of this occurring?

**Comment by Refelinux** [comment]
At 00:00 I receive releases in my country. But I can download them only after half a day.
How could this happen that the previous version of the plug-in did not have this problem, even when I gave you the screen with error, but you still do not understand what's happens... offensively (
Apparently I will have to use previous versions of the plugin...
I also think that there are two reasons why this happened.
You changed the code of size of covers or code for the availability of all tracks in the album from others albums.
You just removed the ability to quickly get the album, and do not know how to fix it. Even with the fact that the original code allowed it to be done. Now I can get the album only if i will waiting release in other countries...
The only thing, for an error test. I can do to help is that I will can give you every day a link to a new album that I can already listen, but you will still not have access to it. You will be able to download these releases by my links through the program, with the old version of the script, even taking into account the fact that in your country it is not yet available

**Comment by TripleFrequency** [comment]
The only way this could be an issue I introduced is with d20e34d, except I already verified it wasn't this based on the example you provided.

I haven't modified the availability code in any meaningful way, and Deezer transcodes all album covers, so what I did with covers would have no effect.

If nobody else can reproduce this issue, then nothing can be done. I am leaving it open for others to provide input, but I doubt meaningful progress will be made without other people encountering this issue, or you providing more example instances. You say you can provide a link every day where it happens, then please do. I need the information if you want the problem fixed.

I get that dealing with issues like this can be frustrating, but I really wish you would consider the development side of it also. Fixing an obscure issue like this is tricky, especially with minimal information. I want to resolve this issue as a means to improving the plugin, but that is difficult if your comments seem to be filled with condescending remarks, but perhaps it is just lost in translation. I just hope you consider that moving forward, so that we can more clearly communicate about this issue, and improve everyone's experience with the plugin.

**Comment by Refelinux** [comment]
I really do not understand how I can more accurately describe the issue... I do not know how to help fix the code... Anyone can encountering this issue of those who live in Europe and in the east of the globe.
And I still can not recognize. You can not understand the principle of error or you do not know how to fix it in the code?

The principle of error - wherever you live, you can not download an album that has already been released in several countries, you must to wait until it comes out in all countries. But with the old version of the plugin you don't need to wait all countries. For example, if I live in Russia, therefore I can upload a new album at 00:00, using 1.2.7. version, but in version 1.3 this opportunity is not available.

**Comment by TripleFrequency** [comment]
[This](https://github.com/TripleFrequency/AthamePlugin.Deezer/compare/d03fb0a5f424d7667e0089e56a3921751c82e085...TripleFrequency:e2df4f10c17ceb77b3f45b800f72f950bd140990) is a comparison of all changes in the code from 1.2.7 until 1.3. Nothing in there suggests a change in the code to be the culprit. I suggest you follow my recommendation of posting every album which is an example of this. I need to be able to reproduce this, or others do, at least.

Also, I would consider this to be an incredibly minor issue. If nothing becomes apparent, this won't be a priority, because it is the difference of only a few hours for getting new albums as a result. Also, because of how authentication with Deezer works, and the downloader works, your suggestion to allow account authentication would over-complicate what the plugin is trying to accomplish. Eventually i'll add authentication, but solely to access private playlists, because downloading within a certain region would require a subscription.

I do fully understand what you are *getting at*, but it simply doesn't make sense. Assuming Deezer uses global release schedules for almost all, if not all tracks, then this issue seems invalid. I can't reproduce it, and the issue seems minor, so I feel it only logical to assume this is some misunderstanding on your end.

As I previously said, I will continue to look at any examples you provide of this, and others, but it isn't a priority, given you say it is only hours later you can download these brand new songs/albums.

If you want to do a proper test of this, I would suggest trying to download something (that doesn't work) on your regular network, then using a U.S. VPN to test whether you can download it, to test these release dates.

**Comment by jonaaa20** [comment]
Just saying but I don't have any issues related to this...

**Comment by Refelinux** [comment]
**jonaaa20** Maybe because you check the albums later than me.

**TripleFrequency**  I do not wait for several hours, I wait half a day... It's too much for me. Soon, I'll give you a new link from December 6th, you will can download it with the old version of the plug-in.

**Comment by Refelinux** [comment]
**TripleFrequency** Test mail sent ! I will communicate through mail with you.

**Comment by TripleFrequency** [comment]
My email address is for business and legal related matters only. **Do not send me emails**, especially concerning matters like this. Posting in the issues board is what community is about, and is required to make a collaborative effort towards fixing problems.

**Comment by Refelinux** [comment]
link for new album - https://www.deezer.com/ru/album/52279612
You may try download it with old version and new version of plugin, but the error will pass in half a day.

**Comment by bascurtiz** [comment]
I tried to d/l the link above with 1.3.0 A2 and also on 1.2.7 RC3.
I confirm you can't d/l it with 1.3.0 A2, u will get an error, see pic:
https://imgur.com/a/PRs9m

Though, although, u can d/l it with 1.2.7 RC3, as show in pic below, it doesnt have any music in it, using Fakin' The Funk spectrum-analysis, see pic 2:
pic 1: https://imgur.com/a/9aCGc
pic 2: https://imgur.com/a/bRjRz

Can you confirm @Refelinux ?

**Comment by Refelinux** [comment]
**bascurtiz** Ahaha ! Yes ! Exactly this strange release just don't have music in the file 
! WTF !
Try this new one - https://www.deezer.com/ru/album/51630922

**Comment by bascurtiz** [comment]
I confirm, with the new link above, I do get good results d/led with 1.2.7-RC3.
But not with 1.3.0-A2. It shows an error.

See the 3 pics in link below:
https://imgur.com/a/cgr0A

**Comment by TripleFrequency** [comment]
I have pushed a new release (1.3-A3), which fixes this issue. Please report back if you continue to have problems.

I appreciate you adding these new links, as it has been integral in fixing the issue. Apparently, the Deezer API doesn't provide image links on new albums, and the plugin wasn't testing for that. Now it does, and you should still see artwork in that case.

**Comment by Refelinux** [comment]
REALLY? HELL YEAH ! I told you it's a problem with the covers! :)

**Comment by Refelinux** [comment]
Yes, it's working now ! Thank You for your great work !

**Comment by bascurtiz** [comment]
I confirm, with 1.3.0-A2, it works now,

Mind you, at this (later) time of day, I could also play the track on the deezer site itself, see pic:
https://imgur.com/a/gWfWj
...which I couldn't a few hours before, see previous reply above.

Also the artwork is showing proper, see pic:
https://imgur.com/a/5Vycu
