### ISSUE TITLE
More than one artist / remixes...

### ISSUE THREAD

**Issue by oO-u-Oo** [TripleFrequency/AthamePlugin.Deezer#4]
When a track contains more than one artist it does not put them or remixes, for example in these albums.
http://www.deezer.com/album/11563378
http://www.deezer.com/album/9099619

This album does not download it, it says"Could not convert string to DateTime: 0000-00-00...............................".
http://www.deezer.com/album/8584912

**Comment by TripleFrequency** [comment]
I've pushed a release which fixes both issues mentioned here. The solution I use (for the Tiesto album) basically appends the remix name, then the featuring artists.

So you would end up with something like `Light Years Away (Extended Radio Edit) (feat. DBX)." In this case, I know it is a bit cluttered, but DBX *is* the featuring artist, and there is no other good solution I could think of.

As for the first album posted, I am open to suggestions. There is nothing identifying them, but I recommend using the track number in your naming scheme, so that you can save them all anyway. I think it is best to leave it as is, because there is no way to distinguish them (by title, at least) under normal circumstances.

**Comment by oO-u-Oo** [comment]
Thanks so much !, some labels do not even care about putting the remixes by laziness, so I put this in the path format {TrackNumber}
