### ISSUE TITLE
Artists

### ISSUE THREAD

**Issue by oO-u-Oo** [TripleFrequency/AthamePlugin.Deezer#7]
The artist name is duplicated, try it with this example.
http://www.deezer.com/track/421758822

**Comment by TripleFrequency** [comment]
This is actually an issue with the Deezer API. You can even see it directly on the page:
![image](https://user-images.githubusercontent.com/6166013/33510270-2cd55a9c-d6d8-11e7-856d-cfecfce9e031.png)
It says that "Oscar Mulero", "Inigo Kennedy", and "Oscar Mulero and Inigo Kennedy" are all primary artists.

The solution I opted for was to only use primary artists in the artist string if they didn't contain " and " or " & ". You can see the fix in commit 055c698.

**Comment by oO-u-Oo** [comment]
its mean, I'll have to do it with mp3tag and the stevehero script?
https://forums.mp3tag.de/index.php?showtopic=14479

**Comment by TripleFrequency** [comment]
I don't follow what you mean? I fixed the bug you mention here, regardless of whether the Deezer API is conducive to the solution.

**Comment by oO-u-Oo** [comment]
Perfect if you have solved it, Thank you and sorry for my misunderstanding.

**Comment by TripleFrequency** [comment]
I pushed a new release (1.2.4) which fixes both this issue and another, so feel free to try it out.

**Comment by oO-u-Oo** [comment]
Let me give you some advice, take things slowly and do not get used to the people who will then be confronted when it stops working, ;)

**Comment by TripleFrequency** [comment]
I figured in the first few days it was more important to push releases more frequently, fixing lots of little bugs, before many people see it, so that as much is fixed as possible. I consider bug fixes (especially with naming conventions) to be worthy of their own release. I would imagine many people, if they downloaded and used this, and the titles were all wrong or had some issue like the ones you have reported, they may just give up on it.

I greatly appreciate all of the issues you have contributed here, as it has been a great help. I don't really have the time to test the plugin out, because I am quite busy, but you have expedited the process by finding rare instances that something doesn't work.

**Comment by oO-u-Oo** [comment]
I have not contributed anything, I wish I could do it as you do but I am not a developer like you.

**Comment by jonaaa20** [comment]
Of course you contributed, feedback is important, don't forget it. Keep doing it and you'll help the dev a lot.
